export const produtos = [
    { nome: "Bola de futebol", tipo: "brinquedo" },
    { nome: "Boneca", tipo: "brinquedo" },
    { nome: "Quebra-cabeça", tipo: "brinquedo" },
    { nome: "Carrinho de controle remoto", tipo: "brinquedo" },
    { nome: "Urso de pelúcia", tipo: "brinquedo" },
    { nome: "Maçã", tipo: "alimento" },
    { nome: "Pão", tipo: "alimento" },
    { nome: "Leite", tipo: "alimento" },
    { nome: "Cenoura", tipo: "alimento" },
    { nome: "Chocolate", tipo: "alimento" },
    { nome: "Chave de fenda", tipo: "objeto" },
    { nome: "Lanterna", tipo: "objeto" },
    { nome: "Garrafa de água", tipo: "objeto" },
]